apiVersion: v2.edp.epam.com/v1alpha1
kind: Stage
metadata:
  name: team-a-sit
spec:
  name: "sit"
  cdPipeline: "test"
  description: "SIT environment for dedicated team"
  qualityGate: "manual"
  triggerType: "is-changed"
  order: 1
  jenkinsStep: "build"
status:
  status: "initialized"
  lastTimeUpdated: 0001-01-01T00:00:00Z